### ISSUE TITLE
update elements.sty and files def (english, french, german,portuges,spanish)

### ISSUE THREAD

**Issue by FBreal** [cgnieder/elements#6]
new atomic elements (113 to 118).
Source wikipedia (fr.wikipedia.org, es.wikipedia.org, en.wikipedia.org, de.wikipedia.org, pt.wikipedia.org)

Thanks and regards

Frédéric Bréal
[elements-miseAjour.zip](https://github.com/cgnieder/elements/files/3090857/elements-miseAjour.zip)

**Comment by cgnieder** [comment]
Thanks!
