### ISSUE TITLE
Support for incomplete configurations

### ISSUE THREAD

**Issue by rafaelpap** [cgnieder/elements#7]
Sometimes I need to write only some of the orbitals of the configuration. For instance, writing electronic transitions is common to do something like

```latex
3d^{3}\ce{^{2}F}\rightarrow 3d^{3}\ce^{2}G}
```

to represent the transition between the spectral term 2F and the 2G from the 3d3 configuration.
If I try `\writeelconf{0,0,0+0+3}` I get 1s0 2s0 2p0 3s0 3p0 3d3 which is not the desired result.

I wonder if there is some workaround.

Yours sincerely,
Rafael

**Comment by cgnieder** [comment]
I suggest the following input
```latex
\documentclass{article}
\usepackage{elements}

\begin{document}

\writeelconf{0,0,0+0+3} \par
\writeelconf{,,++3}

\end{document}
```
in order to get

![grafik](https://user-images.githubusercontent.com/2248538/151658397-c8fc14dd-7228-4af0-b45c-e3a6d6429fcd.png)

This syntax will be supported in the next version.

**Comment by rafaelpap** [comment]
Thanks !!
