### ISSUE TITLE
Shortened electron configuration

### ISSUE THREAD

**Issue by rafaelpap** [cgnieder/elements#8]
After the 0.4 version I believe it's possible to write shortened electrons configurations. From the manual:
[Ar]3d104s1 could be written using:

[\ch{Ar}]\writeelconf{,,++10,1}

**Comment by cgnieder** [comment]
True, but what the manual means to say is that you can't input `\elconf{Cu}` and get [Ar]3d¹⁰4s¹

**Comment by rafaelpap** [comment]
You are right. I just wanted to point out a poor's man option.
